# Generated by Django 4.2.1 on 2023-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="photo"),
        ),
        migrations.AddField(
            model_name="task",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
